Repository effector/next, pull requests merged in 2023-04, with the labels that each got.

#2 Update package.json
  package.json
Labels: bug

#3 Support effector v22.8.0
  src/get-scope.ts
Labels: fix

#7 Update minimal effector version and fix bug
  package.json
  pnpm-lock.yaml
  src/get-scope.ts
Labels: enhancement, fix

#8 Ignore named stores
  src/get-scope.ts
Labels: fix
